openapi: 3.0.0

info:
  title: etonee123x
  version: 1.0.0
  description: etonee123x API
  license:
    name: UNLICENSED
    url: UNLICENSED

security: []

servers:
  - url: https://etonee123x.dev/api

tags:
  - name: FolderData
    description: Folder browsing and files
  - name: Posts
    description: Posts CRUD
  - name: Auth
    description: Authentication

paths:
  /auth:
    $ref: paths/auth.yaml

  /posts:
    $ref: paths/posts.yaml
  /posts/{id}:
    $ref: paths/posts_{id}.yaml

  /folder-data:
    $ref: paths/folder-data.yaml
  /folder-data/all-paths:
    $ref: paths/folder-data_all-paths.yaml

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt